### ISSUE TITLE
Inconsistent Wikidata ID output

### ISSUE THREAD

**Issue by dugost** [culturecreates/artsdata-shortcode#14]
Some profiles display "Wikidata ID: VALUE" in the links bar but not in the venue listings (e.g. ArtSpring).

Some profiles display "Wikidata ID:" in the links bar when no value exists (e.g. Canada's Ballet Jörgen).

If a Wikidata ID does not exist for a member or their venue(s), the <p> "artsdata-wikidata-id" and <p> "artsdata-place-wikidata-id" should be hidden.

**Comment by saumier** [comment]
Stale issue so I am closing it unless I hear back about this.
