### ISSUE TITLE
Wikidata venue labels still not displayed correctly

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-shortcode#16]
Initially, the English labels were displayed fine, but French labels were missing.
When version 1.4 of the plugin was rolled out, labels disappeared.
I checked again today: labels are back but they are displayed as URIs or as "ARRAY".
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/a9bb7bef-af30-4dae-bb1f-556346667a50)

**Comment by saumier** [comment]
@fjjulien I was working on this today, and those labels were displayed temporarily. I removed them. Now they are blank again. The new Artsdata Shortcode plugin 1.4.1 will make them reappear once Ryan deploys.
