### ISSUE TITLE
French translation of default credit line in image title not displayed

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-shortcode#17]
As per this [Asana task](https://app.asana.com/0/0/1203321483279239/f), we decided to direct users to Wikimedia Commons to access image credits:  "Image from Wikimedia Commons. Click on the image to view photo credits." / « Image provenant de Wikimedia Commons. Cliquez sur l'image pour consulter les mentions d'attribution. »

The hyperlink to Wikimedia Commons works fine. However, the default credit line is still only displayed in English, even though Ryan added to the French credit to the translation file.
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/6bd5aaa5-2320-4d79-a477-27edc7e7fd6b)

This is not a major issue. If we can't solve it after another hour or two of work, I can accept that the credit line would only be displayed in English.

**Comment by saumier** [comment]
@fjjulien I added the i18n code for the default image credits in v1.4.1.
