### ISSUE TITLE
French translation issues for ID links, categories and Venue listings

### ISSUE THREAD

**Issue by dugost** [culturecreates/artsdata-shortcode#18]
Minor issues but I figured they should be outlined in case they're not on anyone's list:

***
<img width="926" alt="french-formatting" src="https://github.com/culturecreates/artsdata-shortcode/assets/74065422/9359464b-ad33-4ffa-ac97-0c31fc09b648">

# 1. Colons

I believe colons should be preceded by a space in French (e.g. "Type de membre :" instead of "Type de membre:"). In the code, the space should be non-breaking as well (`Type de membre&nbsp;:`).

Likewise, the IDs in the blue external links bar are missing colons and should be included for consistency with EN (`Identifiant Artsdata&nbsp;:` and `Identifiant Wikidata&nbsp;:`)

***
<img width="1094" alt="venue-alt-tag" src="https://github.com/culturecreates/artsdata-shortcode/assets/74065422/06d2ab02-a2d4-4671-8c14-a2f7799ad8d7">

# 2. Venue Names / ALT Tags
Venues are using the EN names (e.g. National Arts Centre instead of Centre national des Arts). And the ALT tag for venue image uses the EN default on the FR site along with the member's EN name (e.g. `alt="Image of National Arts Centre"` instead of `alt="Image du Centre national des Arts"`).

"Wikidata ID:" for venues also not translated to "Identifiant Wikidata :".

***
<img width="1039" alt="no-map-data" src="https://github.com/culturecreates/artsdata-shortcode/assets/74065422/37e2069c-55bb-49ca-ac12-0b3f97e5c48f">

# 3. Map Data

The "No map data available." line isn't translated either. A separate, semantic point: the wrapping `<p>` tag could be hidden conditionally to keep it out of the DOM when a Leaflet map is present.

**Comment by fjjulien** [comment]
@dugost 

- You are absolutely correct about colons in French: they require a nonbreaking space before the colon.
- Good catch about the translation of venue names and the Wikidata ID field label!

**Comment by dugost** [comment]
Item "1. Colons": This was already taken care of in the language files but my incorrectly modified language files were preventing their output.

Item "2. Venue Names / ALT Tags": Not having any luck with this one. I'll follow up separately about it and some other issues with the language files.

Item "3. Map Data": Same thing in terms of translation. The conditional part, if deemed necessary, would be on Gregory's end.

**Comment by saumier** [comment]
@dugost @fjjulien I regenerated the translation file using Loco Translate in WordPress. I think that may help. The only thing I still see as a problem is the french names of venues which I would need to add from Wikidata. But all other ALT tags, Map Data, Colons should be working now.

**Comment by saumier** [comment]
@dugost Please confirm that release [1.4.2](https://github.com/culturecreates/artsdata-shortcode/releases/tag/v1.4.2) has fixed all except the venue name and close this issue. Thx.

**Comment by saumier** [comment]
@dugost Hi. I finally added the place and performance hall names in french so they are fully bilingual. I also added the remaining english strings for the Wikidata Id and ALT Tags. I regenerated the .po file using Loco Translate in WorkPress and added it to the git repo. Release 1.4.3 should be good. Please take a look and close the issue.

**Comment by dugost** [comment]
@saumier Looks good!

**Comment by fjjulien** [comment]
@dugost I just checked the directory to see the outcome, and I am afraid we have further issues. Most presenting organizations profiles no longer display their venue, be it in English or in French. See https://test.capacoa.ca/en/member/directory/profile/?uri=http://kg.artsdata.ca/resource/K14-14 The only presenting member that still has its venues is the National Arts Centre.

**Comment by dugost** [comment]
@fjjulien I'm unsure why this is happening. @saumier do I need to reload data from the staging admin page or is there something else going on?

**Comment by saumier** [comment]
@fjjulien  I'll take a look into this now.  @dugost I will look into the Shortcode plugin. There is only one data source for the plugin in both staging and production, meaning both staging plugin and production plugin use the same data source from Artsdata, so no need to reload the data.

**Comment by saumier** [comment]
@fjjulien The venues are appearing in test.capacoa.ca.  No change to the shortcode plugin. I had made a mistake with SPARQL in Artsdata. It was returning schema:name instead of rdfs:label.
