### ISSUE TITLE
Incorrect data output in artsdata-place-type

### ISSUE THREAD

**Issue by dugost** [culturecreates/artsdata-shortcode#19]
Some Venue entries on the staging site display the letter "H" one or more times in the place type line (EN and FR). [Good example](https://test.capacoa.ca/en/member/directory/profile/?uri=http://kg.artsdata.ca/resource/K14-63).

`<p class="artsdata-place-type">h, h</p>`

Should an option be run from the admin page to refresh results or is this due to something else?

<img width="1039" alt="weird-h" src="https://github.com/culturecreates/artsdata-shortcode/assets/74065422/3d814e0c-fbd2-4aa4-811c-37d1b9a46a4a">

**Comment by saumier** [comment]
@dugost Sorry about this. It's fixed now in Artsdata. No change made to the plugin code.  I was testing with NAC but the case of EA Rawlinson has a slightly different set of data. I made a fix in Artsdata to cover more cases.  I am still looking into SPEC which should have venues showing but other than that I think this problem will no longer appear.
