### ISSUE TITLE
Biographies not displayed

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-shortcode#21]
The "Biographical Info" for our model lifetime member and our model artist members are not displayed in the development site. (note: this issue was not discussed in today's bi-weekly meeting with Culture Creates.)

The model lifetime member is Richard Stoker:
Username: R Stoker
user_id=152

The model artist will be Rhodnie Désir: 
username: RD Creations
user_id=150

@dugost indicated he needs assistance from @saumier to resolve this issue.

I suspect biographical information is not extracted from the CAPACOA database yet.

Over this [Asana task](https://app.asana.com/0/0/1204697671036992/f), @saumier reported:
>"Regarding Bios, I am blocked.  There is no metadata bio fields in the Wordpress API of the CAPACOA database. You can see all the fields in the link below. 
https://www.capacoa.ca/wp-json/wp/v2/users?per_page=100
>
>If there is a BIO field then Ryan needs to add the field to the list of exported ones in the metadata plugin:
https://github.com/culturecreates/capacoa-artsdata-usermeta/blob/main/capacoa-artsdata-usermeta.php"

The "biographical info" field is not a custom wp_usermeta field. It is a core WordPress user field. It is likely found within the wp_users table. I'm guessing the matching database field is called "description". I was not able to verify this hypothesis, because the data records for our two model members are not displayed in Gregory's link.

I will leave it to the two of you to resolve this issue.

**Comment by saumier** [comment]
@fjjulien The link to the Wordpress data is limited to 100 at a time. So to view the remaining 80 you can move to the next page with an offset of 100 like this https://www.capacoa.ca/wp-json/wp/v2/users?per_page=100&offset=100

In this second page of result you can find the 2 model members and they do have "description" properties that look like good descriptions. I will add these to the plugin.

**Comment by fjjulien** [comment]
@dugost The wp_users "description" field only store the English biographical info. If French translation is not directly stored in the  wp_users table, check in polylang tables. If you can't retrieve the field within a reasonable timeframe, notify me: we'll consider alternative solutions.

**Comment by saumier** [comment]
@dugost The user bios should be appearing now. Please close after checking Richard Stoker.

**Comment by dugost** [comment]
@fjjulien Polylang automatically created the 'description_fr' field. I let @saumier know that it was available to use for FR just like 'description' is for EN.

@saumier The bios appear for Richard and Rhodnie, and no bios appear for other individual type members. But for org type members, the "Biography:" heading is displayed with 'Array' beneath it.
