### ISSUE TITLE
Clean old "performing artist" values from the CAPACOA database

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-shortcode#22]
This is a task for @dugost.

Gregory reported that the CAPACOA database has few records with old `Q713200` ("performing artist") occupation values. This is generating errors in his export-transform-load.

These values should be overridden with `Q483501` ("artist").

**Comment by fjjulien** [comment]
While you are at it, you should also check the database for old "other value and replace them with `Q55107540`.

**Comment by dugost** [comment]
I've isolated all of the members with occupations and changed Q713200 to Q483501 where it made sense. I'll close this and follow up with you separately on how to handle specific records.
