### ISSUE TITLE
Cannot mint capacoa.ca member 151  "CORPUS"

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-shortcode#27]
capacoa.ca member 151 called  "CORPUS" is identified as an individual Person.

This seems wrong. The website is "https://www.corpus.ca/www.corpus.ca".

Please fix the source data in the CAPACOA database before this entity gets minted.

**Comment by fjjulien** [comment]
I refreshed the database in Artsdata, and then I ran an [individual member query](https://s.zazuko.com/3kF9h7h), but CORPUS is still listed as an individual member 15 minutes after the refresh. This means an admin change in member level does impact the logic for infering member types.
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/82e3b7d6-b762-4153-b41e-04ac8fa25f16)

**Comment by fjjulien** [comment]
Next troubleshooting step...

I manually created a new order that matched Chandel's admin change to the membership level (Business member D, with a timestamp June 20, 2023). The old order (as an individual member) is still however still present.
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/8e5e856d-a551-4f8d-b88d-19b7b46d1fb5)

This did not resolve the issue: CORPUS still shows up as an individual member in the query.

**Comment by fjjulien** [comment]
Final troubleshooting step...

I edited the old order. I changed the membership level to "Business Member D". And I refreshed the database.
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/04116197-f47f-4d29-9d63-68498d951043)

CORPUS still has the "individual" member type in Artsdata. 
![image](https://github.com/culturecreates/artsdata-shortcode/assets/78500666/651d7526-4b7b-4345-be7e-e9f25e0779b7)

No matter what I change as an administrator, I am unable to remove or override the condition `Pmpro_approval_12.status = approved`=`TRUE` that Huggin uses to run its inference. 

The only solution that I can see is for @dugost to manually edit the `Pmpro_approval_12.status` in the database.

This particular case highlights how poor and fragile our logic is for inferring member types.

For a future iteration, I recommend that we create an explicit "type" or "instance of" field. This would remove entirely the need to run inferences and would make our data available "as is" by Artsdata or any other reuser.

**Comment by fjjulien** [comment]
Note: We have another member in a similar situation: STO Union (user_id=28).

In their case the change that Chandel made did solve the problem. I'm puzzled...

**Comment by dugost** [comment]
@fjjulien @saumier It would appear PMP doesn't clear or delete fields that are no longer applicable to a particular member type. I'll review the database to see what might cause the discrepancy when changing the membership level for CORPUS versus STO Union. After that, I may also have a recommendation on how to proceed.

**Comment by saumier** [comment]
Here is the data for CORPUS coming from the Capacoa database:

```
 {
    "id": 151,
    "name": "CORPUS",
    "url": "",
    "description": "",
    "link": "https://capacoa.ca/author/corpus/",
    "slug": "corpus",
    "avatar_urls": {
      "24": "https://secure.gravatar.com/avatar/270b84122afc5866a81231dc1e8c25e0?s=24&d=mm&r=g",
      "48": "https://secure.gravatar.com/avatar/270b84122afc5866a81231dc1e8c25e0?s=48&d=mm&r=g",
      "96": "https://secure.gravatar.com/avatar/270b84122afc5866a81231dc1e8c25e0?s=96&d=mm&r=g"
    },
    "meta": [],
    "usermeta": {
      "operating_name1": "CORPUS",
      "operating_name1_language": "en",
      "operating_name2": "",
      "operating_name2_language": "",
      "legal_name": "",
      "legal_name_language": "",
      "also_known_as": "",
      "business_number": "",
      "legal_form": "",
      "charitable_status": "",
      "primary_activity": "",
      "discipline_genre": [
        "dan"
      ],
      "presenting_format": "",
      "occupation": "",
      "website_official": "https://www.corpus.ca/www.corpus.ca",
      "events_page": "",
      "artsdata_id": "",
      "wikidata_id": "",
      "venue_name": "",
      "venue_relationship": "",
      "wikidata_id_venue": "",
      "venue_other_name": "",
      "venue_other_relationship": "",
      "wikidata_id_venue_other": "",
      "terms_conditions": "agree and disclose (v1.1)",
      "pmpro_bcountry": "CA",
      "pmpro_bcity": "Toronto",
      "pmpro_bstate": "ON",
      "pmpro_approval_12": {
        "status": "approved",
        "timestamp": 1678190487,
        "who": 21,
        "approver": "chandelgambles"
      },
      "pmpro_approval_13": ""
    },
    "yoast_head": null,
    "yoast_head_json": null,
    "_links": {
      "self": [
        {
          "href": "https://capacoa.ca/wp-json/wp/v2/users/151"
        }
      ],
      "collection": [
        {
          "href": "https://capacoa.ca/wp-json/wp/v2/users"
        }
      ]
    }
  }
```

**Comment by saumier** [comment]
Here is the data for STO Union from https://www.capacoa.ca/wp-json/wp/v2/users?per_page=100&page=2

It shows  "pmpro_approval_12" is pending, so not typed as an individual member.

```
 {
    "id": 28,
    "name": "STO Union",
    "url": "",
    "description": "",
    "link": "https://capacoa.ca/author/sto-union/",
    "slug": "sto-union",
    "avatar_urls": {
      "24": "https://secure.gravatar.com/avatar/f22b1509e14def5df186ee325e9f1acf?s=24&d=mm&r=g",
      "48": "https://secure.gravatar.com/avatar/f22b1509e14def5df186ee325e9f1acf?s=48&d=mm&r=g",
      "96": "https://secure.gravatar.com/avatar/f22b1509e14def5df186ee325e9f1acf?s=96&d=mm&r=g"
    },
    "meta": [],
    "usermeta": {
      "operating_name1": "STO Union",
      "operating_name1_language": "en",
      "operating_name2": "",
      "operating_name2_language": "",
      "legal_name": "STO Union Theatre Company Inc.",
      "legal_name_language": "en",
      "also_known_as": "",
      "business_number": "890739139",
      "legal_form": "Not-for-profit organization",
      "charitable_status": "Not a charitable organization",
      "primary_activity": "prod",
      "discipline_genre": [
        "oth",
        "the"
      ],
      "presenting_format": "",
      "occupation": "",
      "website_official": "https://stounion.com/",
      "events_page": "",
      "artsdata_id": "",
      "wikidata_id": "",
      "venue_name": "",
      "venue_relationship": "",
      "wikidata_id_venue": "",
      "venue_other_name": "",
      "venue_other_relationship": "",
      "wikidata_id_venue_other": "",
      "terms_conditions": "agree and disclose (v1.1)",
      "pmpro_bcountry": "CA",
      "pmpro_bcity": "Wakefield",
      "pmpro_bstate": "QC",
      "pmpro_approval_12": {
        "status": "pending",
        "timestamp": 1680310764,
        "who": "",
        "approver": ""
      },
      "pmpro_approval_13": ""
    },
    "yoast_head": null,
    "yoast_head_json": null,
    "_links": {
      "self": [
        {
          "href": "https://capacoa.ca/wp-json/wp/v2/users/28"
        }
      ],
      "collection": [
        {
          "href": "https://capacoa.ca/wp-json/wp/v2/users"
        }
      ]
    }
  }
```

**Comment by saumier** [comment]
Closing this issue as "Corpus" has been minted.
